layout_spectrum: 0.9193549
typography_spectrum: 0.8799283
color:
  saturation: 0.8799283
  lightness: 0.6971326
  brandStrength: 0.204686
  brandColors:
    - '#1F1616'
    - '#D0915B'
    - '#544A49'
    - '#AB9A93'
    - '#FBC5B5'
  rhythmicContrast: 0.7222222
name: Canineeducation
