collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.90681
color:
  saturation: 0.6236559
  brandStrength: 0.5179211
  lightness: 0.4856631
  brandColors:
    - '#D0C4AC'
    - '#1E4D53'
    - '#202126'
    - '#998977'
  rhythmicContrast: 1
layout_spectrum: 0.9874552
name: Canineeducation.ca
